/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ettermiprogram;

/**
 *
 * @author SomogyváriMártonPéte
 */
public class Szamla extends javax.swing.JFrame {

    /**
     * Creates new form Szamla
     */
    public Szamla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        esemenyek = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        blokk = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pLista = new javax.swing.JList<>();
        pAsztal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pOssz = new javax.swing.JLabel();
        zAsztal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        zLista = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        zOssz = new javax.swing.JLabel();
        kAsztal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kLista = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        kOssz = new javax.swing.JLabel();
        fAsztal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fLista = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        fOssz = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pOsszEredmeny = new javax.swing.JLabel();
        zOsszEredmeny = new javax.swing.JLabel();
        kOsszEredmeny = new javax.swing.JLabel();
        fOsszEredmeny = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Éttermi számla");

        jToggleButton2.setText("Módosítás");

        jToggleButton3.setText("Blokk nyomtatása");

        javax.swing.GroupLayout esemenyekLayout = new javax.swing.GroupLayout(esemenyek);
        esemenyek.setLayout(esemenyekLayout);
        esemenyekLayout.setHorizontalGroup(
            esemenyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, esemenyekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        esemenyekLayout.setVerticalGroup(
            esemenyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, esemenyekLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(esemenyekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Babgulyás      700 Ft", "Rántott Sajt    900 Ft" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(pLista);

        pAsztal.setText("Piros Asztal:");

        jLabel2.setText("==============================");

        pOssz.setText("Összesen: ");

        zAsztal.setText("Zöld Asztal:");

        jLabel5.setText("==============================");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Gyümölcsleves      700 Ft", "Bécsi szelet             900 Ft", "Somlói galuska      500 Ft" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        zLista.setViewportView(jList2);

        zOssz.setText("Összesen: ");

        kAsztal.setText("Kék Asztal:");

        jLabel8.setText("==============================");

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Gyümölcsleves      700 Ft", "Rántott sajt             900 Ft" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        kLista.setViewportView(jList3);

        kOssz.setText("Összesen: ");

        fAsztal.setText("Fehér Asztal:");

        jLabel11.setText("==============================");

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Bécsi szelet             1200 Ft" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        fLista.setViewportView(jList4);

        fOssz.setText("Összesen: ");

        jLabel13.setText("______________________________");

        jLabel14.setText("______________________________");

        jLabel15.setText("______________________________");

        jLabel16.setText("______________________________");

        pOsszEredmeny.setText("1600 Ft");

        zOsszEredmeny.setText("2500 Ft");

        kOsszEredmeny.setText("1700 Ft");

        fOsszEredmeny.setText("1200 Ft");

        javax.swing.GroupLayout blokkLayout = new javax.swing.GroupLayout(blokk);
        blokk.setLayout(blokkLayout);
        blokkLayout.setHorizontalGroup(
            blokkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blokkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(blokkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(blokkLayout.createSequentialGroup()
                        .addGroup(blokkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(blokkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, blokkLayout.createSequentialGroup()
                                    .addComponent(zAsztal)
                                    .addGap(14, 14, 14))
                                .addComponent(jLabel5))
                            .addGroup(blokkLayout.createSequentialGroup()
                                .addComponent(zOssz)
                                .addGap(28, 28, 28)
                                .addComponent(zOsszEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(blokkLayout.createSequentialGroup()
                        .addGroup(blokkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(blokkLayout.createSequentialGroup()
                                .addComponent(kOssz)
                                .addGap(26, 26, 26)
                                .addComponent(kOsszEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(blokkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, blokkLayout.createSequentialGroup()
                                    .addComponent(fOssz)
                                    .addGap(30, 30, 30)
                                    .addComponent(fOsszEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kAsztal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fAsztal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pAsztal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, blokkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(blokkLayout.createSequentialGroup()
                                        .addComponent(pOssz)
                                        .addGap(28, 28, 28)
                                        .addComponent(pOsszEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(zLista, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kLista, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fLista, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        blokkLayout.setVerticalGroup(
            blokkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blokkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pAsztal)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(9, 9, 9)
                .addGroup(blokkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pOssz)
                    .addComponent(pOsszEredmeny))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(zAsztal)
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zLista, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blokkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zOsszEredmeny)
                    .addGroup(blokkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(zOssz)))
                .addGap(35, 35, 35)
                .addComponent(kAsztal)
                .addGap(2, 2, 2)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kLista, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blokkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kOssz)
                    .addComponent(kOsszEredmeny))
                .addGap(39, 39, 39)
                .addComponent(fAsztal)
                .addGap(2, 2, 2)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fLista, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blokkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fOssz)
                    .addComponent(fOsszEredmeny))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esemenyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(blokk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blokk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(esemenyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Szamla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Szamla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Szamla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Szamla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Szamla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blokk;
    private javax.swing.JPanel esemenyek;
    private javax.swing.JLabel fAsztal;
    private javax.swing.JScrollPane fLista;
    private javax.swing.JLabel fOssz;
    private javax.swing.JLabel fOsszEredmeny;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JLabel kAsztal;
    private javax.swing.JScrollPane kLista;
    private javax.swing.JLabel kOssz;
    private javax.swing.JLabel kOsszEredmeny;
    private javax.swing.JLabel pAsztal;
    private javax.swing.JList<String> pLista;
    private javax.swing.JLabel pOssz;
    private javax.swing.JLabel pOsszEredmeny;
    private javax.swing.JLabel zAsztal;
    private javax.swing.JScrollPane zLista;
    private javax.swing.JLabel zOssz;
    private javax.swing.JLabel zOsszEredmeny;
    // End of variables declaration//GEN-END:variables
}
